### ISSUE TITLE
Allow user to change size of width lines/dots

### ISSUE THREAD

**Issue by isaacvandor** [wingtorres/morphometrix#1]
This is definitely more of a feature enhancement than a bug, but it would be nice to adjust the size of the lines/dots when measuring width. They're pretty small as is, so it could be good to add a slider or other option for someone to adjust the size.

Also, if you want others to contribute, adding a `CONTRIBUTING.MD` or "how to add an issue" doc could be helpful.

**Comment by wingtorres** [comment]
Thanks for the feedback @isaacvandor ! I think it would be great to add some customization options down the line - I just don't think I have the bandwidth right now to implement it :). The option to change the color of the dots and lines would also be good to have especially if the image subject doesn't contrast. Perhaps in the meantime enterprising users can modify the source code directly to customize their use of it. Wherever the 
```
setPen(QtGui.QPen(QtGui.QColor('')) 
```
method shows up, that's where the line colors are set and the dot size is set by the lines

```
                s = 10  #dot size
                self.scene.ellipseItem = QGraphicsEllipseItem(0, 0, s, s)
```
