### ISSUE TITLE
Beta version 1.2.0 testing

### ISSUE THREAD

**Issue by dasweeney4423** [wingtorres/morphometrix#16]
## System Information 

Operating System (e.g. Mac OS Monterey, Windows 11, Ubuntu Lunar Lobster):  Windows 11
Chip (e.g. x86-64, Mac M1):  64
Python version:  3.10.8

I used the windows exe app for testing

## Verify that you can carry out the following actions

Mark inside the brackets with an [x] to 

- [x ] Measure a length w/ Bezier curve 
- [see feedback below] Measure a length w/o Bezier curve
- [x ] Measure width segments w/ Bezier curve
- [see feedback below] Measure width segments w/o Bezier curve
- [x] Measure an angle
- [x] Measure an area
- [see error] Export measurements saves a .csv and .png w/ the correct measurements

## If you encounter an error, please copy paste the error log info here. Attach the .csv/.png to the issue if possible.
Exporting worked fine with the exception of when exporting length measurements that did not include a bezier fit length. Put another way to help clarify the conditions that throw errors, if a piecewise length measurement was made but no bezier fit length is made, the attached error would be spit out, the measurements csv file would only contain metadata, and no measurement image would be returned. However, if piecewise and bezier fit lines are made, or if no lengths are made and just angles and/or areas are made, exporting data works fine. 
[2023-06-28_Morphometrix_Crashlog.txt](https://github.com/wingtorres/morphometrix/files/11898729/2023-06-28_Morphometrix_Crashlog.txt)
[210716_I2O_S5_U2_DJI0005_00_02_45_vlc00009.csv](https://github.com/wingtorres/morphometrix/files/11898730/210716_I2O_S5_U2_DJI0005_00_02_45_vlc00009.csv)

## Please provide additional feedback and/or suggestions below
- When measuring piecewise lengths, nan values are returned for lengths regardless of how many segments make up the piecewise length. 
- If both a bezier fit and a piecewise line have been made, width measurements will always pop up for the most recent bezier fit. For example, if I make 3 piecewise lengths and 7 bezier fit lengths, measured widths will only pop up for the 7th bezier fit curve regardless of what length was created last.
- measure widths points only can appear for piecewise lines with one segment (this makes sense somewhat but there may be a benefit of making this more flexible)
- width segments for piecewise lines are not accurately spaced across the length of the line

**Comment by cbirdferrer** [comment]
Hi David! 
Thanks for providing this feedback, we really appreciate it! We've incorporated fixes for these comments into the v2 release, so keep an eye out for that!

Thanks! 
the MMX team
