### ISSUE TITLE
Another look at v2

### ISSUE THREAD

**Issue by RiccardoCicciarella** [wingtorres/morphometrix#17]
## System Information 

Operating System: Windows 11  
Chip (e.g. x86-64, Mac M1):  
Python version:  3.10

## Verify that you can carry out the following actions

Mark inside the brackets with an [x] to 

- [ x] Measure a length w/ Bezier curve 
- [ x] Measure a length w/o Bezier curve
- [ x] Measure width segments w/ Bezier curve
- [ x] Measure width segments w/o Bezier curve
- [ x] Measure an angle
- [ x] Measure an area
- [ x] Export measurements saves a .csv and .png w/ the correct measurements

## Please provide additional feedback and/or suggestions below
I already provided feedback few days before, but I just realized something else as I was using this version. When measuring widths on narrower body parts of an animal (specifically a dolphin), the crosshair from one side obscures the body contour of the other side. It'd be great to have the option to change the size of the crosshair to avoid it being in the way of measurements.
Thank you again very much for your work!

**Comment by cbirdferrer** [comment]
Hi Riccardo! 
Thanks for providing this feedback, we really appreciate it! We've incorporated fixes for these comments into the v2 release, so keep an eye out for that!

Thanks! 
the MMX team
