### ISSUE TITLE
MorphoMetrix version 2 beta testing

### ISSUE THREAD

**Issue by ashleyblawas** [wingtorres/morphometrix#18]
## System Information 

Operating System: Windows 11 
Chip: Intel(R) Core(TM) i7-8550U
Python version: 3.10.8

## Verify that you can carry out the following actions

Mark inside the brackets with an [x] to 

- [X] Measure a length w/ Bezier curve 
- [ ] Measure a length w/o Bezier curve
- [X] Measure width segments w/ Bezier curve
- [ ] Measure width segments w/o Bezier curve
- [X] Measure an angle
- [X] Measure an area
- [X] Export measurements saves a .csv and .png w/ the correct measurements

## If you encounter an error, please copy paste the error log info here. Attach the .csv/.png to the issue if possible.
**Piecewise length measurement error log**
System: Windows
OS: nt
Python Version: 3.10.8
Python Implementation: CPython
Release: 10
Version: 10.0.22621
Machine: AMD64
Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel

Traceback (most recent call last):
  File "morphometrix\__main__.py", line 437, in export_measurements
TypeError: can't multiply sequence by non-int of type 'float'

[210716_I2O_S5_U2_DJI0005_00_02_45_vlc00009.csv](https://github.com/wingtorres/morphometrix/files/11923059/210716_I2O_S5_U2_DJI0005_00_02_45_vlc00009.csv)

## Please provide additional feedback and/or suggestions below
A couple of times I tried to click the undo button (to undo the second point placement of the Bezier curve length measurement and to undo moving a crosshair for the width measurement) but it did not seem to undo the move. It did work when I was doing a Piecewise measurement and I clicked undo mid-measurement.

When I measure the length with Piecewise selected it allows me to make the measurement but when I double click to end the measurement, although it ends the line, the bottom left still says "Click to place next point" and the Measure Width button is grayed out. When I click export after making the Piecewise length measurement MorphoMetrix crashes (log and csv above). 

When I tried to do a Piecewise length measurement directly following a Bezier curve measurement (i.e. same window) I can successfully export the measurements without it crashing but the measurement appeared as "nan" in the csv output.

**Comment by cbirdferrer** [comment]
Hi Ashley! 
Thanks for providing this feedback, we really appreciate it! We've incorporated fixes for these comments into the v2 release, so keep an eye out for that!

Thanks! 
- the MMX team
