### ISSUE TITLE
More text to orient user on home screen

### ISSUE THREAD

**Issue by bw4sz** [wingtorres/morphometrix#2]
It's a bit cumbersome to toggle between the paper/README/GUI to keep track of each of the steps. Please consider adding some text, each on hover, on in the sidebar that helps guide the user. I think this would reduce the barrier to entry. 
Thanks!

**Comment by wingtorres** [comment]
@bw4sz thanks for the suggestion! I agree that this would increase usability. The most recent update integrates the README as a .html the user can scroll through as a widget below the other options on the opening frame. Do you think that does the trick?

![Screen Shot 2019-12-15 at 10 45 58 AM](https://user-images.githubusercontent.com/28067578/70869359-25cd0e00-1f58-11ea-808d-56ec84315346.jpeg)
