### ISSUE TITLE
Width measuring lines below image

### ISSUE THREAD

**Issue by CharlotteBahamas2017** [wingtorres/morphometrix#8]
I'm using __MorphoMetriX_V3_test_220122__.py on a macbook pro running macOS Monterey 12.1

Once you have loaded an image, if you 'measure' the whale from the bottom of the picture to the top of the picture using 'Measure Lengths', and then hit 'Measure Widths' the measure lines are below the image - it works correctly if you measure from the top to the bottom

Attached an image showing this

Feel free to contact me for any more info.

Charlotte Dunn
cdunn@bahamaswhales.org
<img width="834" alt="Screenshot 2022-02-04 at 8 44 35 AM" src="https://user-images.githubusercontent.com/30603126/152539204-359c81d6-e329-4643-9e44-e57a752ca98c.png">

**Comment by wingtorres** [comment]
HI  @CharlotteBahamas2017 sorry you are having this issue! However, I cannot seem to reproduce it. Are you using the latest version from github?

**Comment by CharlotteBahamas2017** [comment]
hi hi

I’m using this version that KC sent me in an email

__MorphoMetriX_V3_test_220122__.py

**Comment by wingtorres** [comment]
hmmm okay can you just try "git clone https://github.com/wingtorres/morphometrix.git" then run morphometrix from within that directory w/ "python -m morphometrix"? You'll need to activate an environment with the correct dependencies installed beforehand.

**Comment by CharlotteBahamas2017** [comment]
hi

that didn’t work

**Comment by wingtorres** [comment]
can you tell me the error message you receive?

**Comment by CharlotteBahamas2017** [comment]
hi - sure - I attached an image of it

‘morphometrix’ is a package and cannot be directly executed

**Comment by wingtorres** [comment]
are you using the -m flag? `python -m morphometrix` works for me.

**Comment by CharlotteBahamas2017** [comment]
yep ..

**Comment by wingtorres** [comment]
hmmm okay... Would you show me the output of both `conda list` and `pip list`?

**Comment by CharlotteBahamas2017** [comment]
sure

conda list:

(qt6) ***@***.*** ~ % 
(qt6) ***@***.*** ~ % conda list
# packages in environment at /Users/lotts/miniconda3/envs/qt6:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py38h50d1736_1    conda-forge
collatrix                 1.0.8                    pypi_0    pypi
dbus                      1.13.18              h18a8e69_0  
easygui                   0.98.2                   pypi_0    pypi
expat                     2.4.4                he49afe7_0    conda-forge
gettext                   0.19.8.1             h1f1d5ed_1    conda-forge
glib                      2.55.0                        0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
jpeg                      9e                   h0d85af4_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libcxx                    12.0.0               h2f01273_0  
libffi                    3.3                  hb1e8313_2  
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
ncurses                   6.3                  hca72f7f_2  
numpy                     1.22.1           py38h9d72dae_0    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
pandas                    1.4.0            py38ha53d530_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pillow                    9.0.0                    pypi_0    pypi
pip                       21.2.4           py38hecd8cb5_0  
pyqt                      5.9.2            py38h655552a_2  
pyqt6                     6.2.2                    pypi_0    pypi
pyqt6-qt6                 6.2.2                    pypi_0    pypi
pyqt6-sip                 13.2.0                   pypi_0    pypi
pyqt6-webengine           6.2.1                    pypi_0    pypi
pyqt6-webengine-qt6       6.2.2                    pypi_0    pypi
python                    3.8.12               h88f2d9e_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
qt                        5.9.7                h8cf7e54_3    conda-forge
readline                  8.1.2                hca72f7f_1  
scipy                     1.7.3            py38hd329d04_0    conda-forge
setuptools                58.0.4           py38hecd8cb5_0  
sip                       4.19.8           py38h0a44026_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h707629a_0  
tk                        8.6.11               h7bc2e8c_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h4dc903c_4  
(qt6) ***@***.*** ~ %

**Comment by CharlotteBahamas2017** [comment]
(qt6) ***@***.*** ~ % pip list
Package             Version
------------------- ---------
certifi             2021.10.8
collatrix           1.0.8
easygui             0.98.2
numpy               1.22.1
pandas              1.4.0
Pillow              9.0.0
pip                 21.2.4
PyQt6               6.2.2
PyQt6-Qt6           6.2.2
PyQt6-sip           13.2.0
PyQt6-WebEngine     6.2.1
PyQt6-WebEngine-Qt6 6.2.2
python-dateutil     2.8.2
pytz                2021.3
scipy               1.7.3
setuptools          58.0.4
six                 1.16.0
wheel               0.37.1
(qt6) ***@***.*** ~ %

**Comment by wingtorres** [comment]
That all looks good to me. Can you tell me the output of `ls` from the same location you tried `python -m morphometrix`? Thanks for your patience - I'm sure we will figure it out.

**Comment by CharlotteBahamas2017** [comment]
(qt6) ***@***.*** ~ % ls
Applications						***@***.*** Creative Cloud Files
Creative Cloud Files					fig4_rvw2.pdf
Creative Cloud Files (archived) (1)			foo.eps
Desktop							gadm36_BHS_0_sp.rds
Desktop.png						get-pip.py
Desktop.res.png						iCloud Drive (Archive)
Desktop\bigger.clk					installs.jsd
Desktop\md245a03_1_00_48_841.clk			java.log.10950
Documents						java.log.11005
Downloads						java.log.1260
Dropbox							java.log.1387
Google Drive						java.log.17039
Library							java.log.17863
Miniconda3-py39_4.10.3-MacOSX-x86_64 2.42.40 PM.sh	java.log.2281
Movies							java.log.2381
Music							java.log.2576
MyBiminiShapefile.dbf					java.log.2846
MyBiminiShapefile.prj					java.log.3630
MyBiminiShapefile.shp					java.log.690
MyBiminiShapefile.shx					java.log.986
Pictures						lib
Public							marine
Raven Pro						marmap_coord_-82;22;-77;26.5_res_1_anti.csv
Raven Pro 1.4.aif					matlab_crash_dump.11384-1
Raven Pro 1.6						matlab_crash_dump.11678-1
Relocated Items						matlab_crash_dump.187-1
Rplot.jpeg						matlab_crash_dump.3213-1
Rplot01.eps						matlab_crash_dump.8868-1
Rplot02.pdf						matlab_crash_dump.9903-1
Rplot03.png						miniconda3
Send Registration					morphometrix
Sites							opt
Tresors							personal
Untitled.pdf.png					profiles.bin
Untitled.png						rosm.cache
Zotero							socnetv-data
(qt6) ***@***.*** ~ %

**Comment by wingtorres** [comment]
okay hopefully this will work. Can you `cd morphometrix` then try running python -m morphometrix from there? I assume the morphometrix directory is what you just cloned from github.

**Comment by CharlotteBahamas2017** [comment]
hi

ok that works but same behaviour, measure from right to left and the width lines are not on the whale

**Comment by wingtorres** [comment]
Okay great! We should be using the same code now. Makes it especially strange that you are still getting the error though... I just tested it with the image you posted initially with the ticket and the widths appear in the correct location.

**Comment by wingtorres** [comment]
would you post four examples starting from right/left and up/down?

**Comment by CharlotteBahamas2017** [comment]
do you want photos or a video?

**Comment by wingtorres** [comment]
Four of the same photo with lengths drawn from each of the four cardinal directions with corresponding widths would be great. That might help us diagnose what is going on
